{{- define "common.istio_dr_mutual_tls" -}}
{{- range $idx, $dr := .Values.destinationRules }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule #usado para rotear uma solicitacao ao servico correspondente
metadata:
  name: {{ $dr.name }}
spec:
  host: {{ $dr.name }}
{{- if $dr.subsets }}
{{- with $dr.subsets }}
  subsets:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL #permite seguranca dentro da malha de servicos (internamente), ou seja, garantir a autenticidade do servico e seus clientes dentro do cluster.
---
{{- end -}}
{{- end -}}
